[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :0 -screen 0 1280x720x24
priority=1

[program:x11vnc]
command=/usr/bin/x11vnc -display :0 -nopw -forever -shared -rfbport 5900
priority=2

[program:chromium]
command=/usr/bin/chromium-browser --no-sandbox --disable-gpu
priority=3
